# Generated by Django 5.0.1 on 2024-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.IntegerField(choices=[(1, 'moblie'), (2, 'shoes'), (3, 'clothes')])),
                ('pdetails', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
